### ISSUE TITLE
2024.2 not installing with poetry on linux

### ISSUE THREAD

**Issue by chrisg564** [ansys/pyworkbench#100]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

This might be a user error on my end, but I am trying to update from pyansys `2024.1.7` to `2024.2.0` for Ansys Notebook. We are using poetry to manage our packages, but `2024.2.0` fails because I think `pyworkbench` relys on `wmi` which requires `pywin32`. I don't think this will work on linux, which is what our notebook image is based on using python `3.9.12`. 

<img width="864" alt="Screenshot 2024-07-10 at 1 26 45 PM" src="https://github.com/ansys/pyansys/assets/37278062/59c43590-8fb9-4a53-9c02-578491a23621">

Most packages that have pywin32 as a requirement with the sys_platform being windows like this:
<img width="517" alt="Screenshot 2024-07-10 at 1 38 04 PM" src="https://github.com/ansys/pyansys/assets/37278062/741a5065-1fb5-44a7-b784-851645e80180">

However, wmi adds the dependency like this: 
<img width="207" alt="Screenshot 2024-07-10 at 1 38 32 PM" src="https://github.com/ansys/pyansys/assets/37278062/1f2743cf-fc84-4d68-aba4-77c00fc23c61">

If this is just an issue on my end, please just close the issue.

### 📝 Steps to reproduce

- Create a poetry project with python 3.9.12 (on mac or linux)
- Add pyansys[all] 2024.2.0

### 💻 Which operating system are you using?

Linux

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
pyansys 2024.2.0
```

**Comment by chrisg564** [comment]
I guess this may lie in the way poetry resolves package dependencies. My build action doesn't even try to download `wmi`, it tries to get `pywin32` before and fails to find any versions that work for my environment.

**Comment by franknli** [comment]
The fix is part of release 0.5.0.
