### ISSUE TITLE
Save and Archive Feature with Workbench Client

### ISSUE THREAD

**Issue by abhishekchitwar** [ansys/pyworkbench#127]
### 📝 Description of the feature

I would like to request an enhancement for **saving** and **archiving** projects in the Workbench Client. 

This enhancement involves the use of the `launch_workbench()` function.

### 💡 Steps for implementing the feature

Implement methods such as save_project and archive_project.

- Use the following code to save a project:

```python

def save_project(self, project_name):  
  workdir = GetServerWorkingDirectory()  
  path = os.path.join(workdir, f"{project_name}.wbpj")  
  save_string = f"""import os  
workdir = GetServerWorkingDirectory()  
path = os.path.join(workdir, "{project_name}.wbpj")  
Save(FilePath=path, Overwrite=True)"""  
  self.run_script_string(save_string)  

 ```

- Use the following code to archive a project:

```python
def archive_project(self, project_name):  
  workdir = GetServerWorkingDirectory()  
  path = os.path.join(workdir, f"{project_name}.wbpz")  
  archive_string = f"""import os  
workdir = GetServerWorkingDirectory()  
path = os.path.join(workdir, "{project_name}.wbpz")  
Archive(FilePath=path , IncludeExternalImportedFiles=True)"""  
  self.run_script_string(archive_string)  
```

**Comment by franknli** [comment]
This is now implemented by the new download_project_archive function, which will be available as release 0.7.0.
