### ISSUE TITLE
Import wbjn script fails 

### ISSUE THREAD

**Issue by tizianrot** [ansys/pyworkbench#43]
If I try to run a previously recorded script that imports an aedt project:
- from the workbench GUI works just fine
- from a script through pyworkbench gives an error and does not perform the operation, please see the attached screenshot: 
![ImportMaxwellError](https://github.com/ansys-internal/pyworkbench/assets/88496115/e15e23b9-d25e-4c5a-9e3c-26e0bff71aa1)

FYI: the method: wb.upload_file() does not work if used with Ansys Electronics Desktop files, is it meant for workbench projects only?
Thank you very much for your help

**Comment by franknli** [comment]
This should be fixed by now.
