### ISSUE TITLE
Clarifiy version compatibilty with Workench release

### ISSUE THREAD

**Issue by rokamoto26** [ansys/pyworkbench#99]
### Description of the modifications

In the PyWorkbench documentation,  there are no description of version compatibility with Workench releases ( it seems 2024R1 and R2 are supported at the moment) 
To improve this, please add a page explaining this like https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html

### Useful links and references

https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html

**Comment by franknli** [comment]
Added version requirement in getting-started document, per release 0.6.0.
